#-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#                                                                                     Networks  
#-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

networks:
  frontend-bridge:
    name: frontend-bridge
    external: true

services: 

  #-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  #                                                                                     Spotweb  
  #-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

  cursor:
    image: danigeus/cursor-vnc:latest
    container_name: cursor
    build:
        context: .
        dockerfile: Dockerfile
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Amsterdam
      - VNC_PASSWORD=geheim123
    networks:
      - frontend-bridge
    ports:
      - 9971:80
      - 9500:5900
    volumes:
      - /volume1/docker/volumes/test:/test
    restart: unless-stopped
